Add new python script to periodically capture images with the camera
BloodFutur/geicar pull request #25
Opened 2024-11-14 20:56 UTC by Soso0400

2024-11-14 21:45 UTC, BloodFutur requested changes
It is great but in my case there is a buffering problem. Check my comment to fix the problem. Try it on your side to check whether it creates new bugs.

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +# Paramètres
Please write comments in english as the project is in english.

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +    exit()
You can add a parameter to the exit function. It is the status code. Usually 0 = OK, 1 = Error

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +
When I try it on my computer, the 5 first pictures are the same. 
You can reduce the size of the VideoCapture buffer by using this line `cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)`.
It means that the two first images will be the same. To fix that I duplicated line 25 (` ret, frame = cap.read()
`) and now all pictures are taken on time.
Could you try that on your side please?

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +    print("Erreur: Impossible d'accéder à la webcam.")
Write errors in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +            print("Erreur: Impossible de lire une frame.")
Write errors in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        # Capture de l'image
Write comments in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        # Génération d'un nom unique pour l'image avec horodatage
Write comments in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        # Sauvegarde de l'image
Write comments in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        # Pause pour l'intervalle spécifié
Write comments in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        print(f"Image capturée et enregistrée : {image_path}")
Console messages should be written in English

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +# Libération de la caméra et fermeture des fenêtres
Write comments in English please ;)

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +        image_path = os.path.join(save_directory, f"image_{timestamp}.jpg")
If the period is less than 1 second, what happens? The first image is overridden?

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +try:
Nice error handling

2024-11-14 21:45 UTC, BloodFutur commented on ImageCapture/webcam_image_capture.py
> +    while True:
I wonder if there is a better way to periodically call this function. `while True` loops and `time.sleep` can make unexpected behaviors in some cases.

2024-11-15 10:34 UTC, Soso0400 commented on ImageCapture/webcam_image_capture.py
> +try:
thank you :)

2024-11-15 14:23 UTC, BloodFutur requested changes
Very good. Fix overridden pictures behavior when the period is < 1s and it will be perfect.

2024-11-17 11:42 UTC, BloodFutur approved these changes

2024-11-17 12:21 UTC, merged